# Generated by Django 3.2.18 on 2023-07-18 06:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20230718_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Подробное описание'),
        ),
    ]
