# Generated by Django 3.2.18 on 2023-07-26 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_agency_description_long'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agency',
            new_name='Place',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='agency_title',
        ),
        migrations.AddField(
            model_name='picture',
            name='place_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_images', to='places.place', verbose_name='Название бюро'),
        ),
    ]
