# Generated by Django 3.2.18 on 2023-07-31 06:28

from django.db import migrations


def copy_model(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    Place_new = apps.get_model('places', 'Place_new')
    for place in Place.objects.iterator():
        Place_new.objects.get_or_create(
            title=place.title,
            description_short=place.description_short,
            description_long=place.description_long,
            latitude=place.latitude,
            longitude=place.longitude)


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_place_new'),
    ]

    operations = [migrations.RunPython(copy_model)
    ]
