# Generated by Django 3.2.18 on 2023-07-31 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20230731_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='agency_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_titles', to='places.place_new', verbose_name='Название бюро'),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
