# Generated by Django 3.2.18 on 2023-07-31 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20230731_1044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place_new',
            new_name='Place',
        ),
    ]
