# Generated by Django 3.2.18 on 2023-07-31 06:56

from django.db import migrations

def copy_picture_model(apps, schema_editor):
    Picture = apps.get_model('places', 'Picture')
    Picture_new = apps.get_model('places', 'Picture_new')
    for picture in Picture.objects.iterator():
        Picture_new.objects.get_or_create(
            number=picture.number,
            image=picture.image,
            sight=picture.agency_title)

class Migration(migrations.Migration):
    
    dependencies = [
        ('places', '0012_picture_new'),
    ]

    operations = [migrations.RunPython(copy_picture_model)
    ]
