# Generated by Django 3.2.18 on 2023-07-31 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20230731_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
