# Generated by Django 3.2.18 on 2023-07-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_delete_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picture_new',
            new_name='Picture',
        ),
    ]
