# Generated by Django 3.2.18 on 2023-08-01 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_rename_picture_new_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Номер изображения')),
                ('image', models.ImageField(db_index=True, upload_to='', verbose_name='Фотография')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_images', to='places.place', verbose_name='Достопримечательность')),
            ],
            options={
                'verbose_name': 'Фотография достопримечательности',
                'verbose_name_plural': 'Фотографии достопримечательности',
                'ordering': ['number'],
            },
        ),
    ]
