# Generated by Django 3.2.18 on 2023-08-01 06:24

from django.db import migrations


def copy_picture_model(apps, schema_editor):
    Picture = apps.get_model('places', 'Picture')
    Picture_2 = apps.get_model('places', 'Picture_2')
    for picture in Picture.objects.iterator():
        Picture_2.objects.get_or_create(
            number=picture.number,
            image=picture.image,
            place=picture.sight)


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_picture_2'),
    ]

    operations = [migrations.RunPython(copy_picture_model)
    ]
