# Generated by Django 3.2.18 on 2023-08-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_auto_20230801_1024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
