# Generated by Django 3.2.18 on 2023-08-01 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_delete_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picture_2',
            new_name='Picture',
        ),
    ]
