# Generated by Django 3.2.18 on 2023-08-02 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_rename_picture_2_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Достопримечательность'),
        ),
    ]
